CREATE DATABASE typingtestapp;

--set extension
CREATE TABLE users(
  user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_name VARCHAR(40) NOT NULL,
  user_email VARCHAR(255) NOT NULL UNIQUE,
  email_token VARCHAR(255),
  user_verified BOOLEAN NOT NULL DEFAULT false,
  user_password VARCHAR(255) NOT NULL,
  pwd_reset_token VARCHAR(255),
  user_date_time DATE NOT NULL
);

--insert dummy users (Just create a user on account so that the date is autogenerated)
-- INSERT INTO users(user_name, user_email, user_password) VALUES ('Guest Account', 'guests@gmail.com', 'Randpass1@asdfwasdfwasdf');

-- Score bonus stored here is purely based on the difficulty of the test score. Additional bonus will be added for duration, etc. 
CREATE TABLE testSettings(
  testSettings_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  name VARCHAR(40) NOT NULL,
  settings text[] NOT NULL,
  difficulty_level VARCHAR(50),
  selected BOOLEAN NOT NULL,
  is_default BOOLEAN NOT NULL,
  scoreBonus INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- INSERT INTO testSettings(name, settings, selected, is_default) VALUES ('Very Easy', ARRAY ['all lower case', 'no punctuation'], false, true );
-- INSERT INTO testSettings(name, settings, selected, is_default) VALUES ('easy', ARRAY ['all lower case', 'Digits 0 - 9'], false, true );
-- INSERT INTO testSettings(name, settings, selected, is_default) VALUES ('medium', ARRAY [''], true, true );
-- INSERT INTO testSettings(name, settings, selected, is_default) VALUES ('Very Hard', ARRAY ['PascalCase', 'camelCase', 'complex words', 'MiXeDcAsE'], false, true );


CREATE TABLE score(
  score_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  difficulty_level VARCHAR(50),
  test_name VARCHAR(50) NOT NULL,
  total_chars INTEGER NOT NULL,
  correct_chars INTEGER NOT NULL,
  misspelled_chars INTEGER NOT NULL,
  cpm INTEGER NOT NULL,
  wpm INTEGER NOT NULL,
  test_score INTEGER NOT NULL,
  test_accuracy INTEGER NOT NULL,
  test_time_sec INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  screen_size_info VARCHAR(255),
  difficulty_name VARCHAR(50),
  difficulty_settings VARCHAR[],
  coins_spent INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE images(
  image_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  profile_pathname VARCHAR(75),
  start_menu_1_pathname VARCHAR(75),
  start_menu_2_pathname VARCHAR(75),
  game_over_pathname VARCHAR(75),
  profile_hex_code VARCHAR(50),
  start_menu_1_hex_code VARCHAR(50),
  start_menu_2_hex_code VARCHAR(50),
  game_over_hex_code VARCHAR(50),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);


-- To add a column
-- ALTER TABLE score ADD COLUMN coins_spent INTEGER NOT NULL DEFAULT 0;