import Link from "next/link";
import { PracticeExperience } from "@/components/practice/practice-experience";
import type { PracticeDefinition } from "@/lib/practice/registry";

export function FocusedPracticePage({ practice }: { practice: PracticeDefinition }) {
  return (
    <>
      <section className="pt-10 sm:pt-14"><div className="page-shell max-w-4xl"><p className="eyebrow">Focused typing practice</p><h1 className="heading-lg mt-2">{practice.h1}</h1><p className="body-lg mt-4">{practice.intro}</p></div></section>
      <PracticeExperience practice={practice} />
      <section className="bg-camp-paper py-14 sm:py-16"><div className="page-shell grid gap-12 lg:grid-cols-2"><div><p className="eyebrow">Skill focus</p><h2 className="heading-md mt-2">What this exercise trains</h2><p className="mt-4 leading-7 text-camp-muted">{practice.trains}</p></div><div><p className="eyebrow">Technique</p><h2 className="heading-md mt-2">Finger responsibilities</h2><p className="mt-4 leading-7 text-camp-muted">{practice.fingers}</p></div></div></section>
      <section className="section-pad"><div className="page-shell grid gap-12 lg:grid-cols-2"><div><p className="eyebrow">Watch for</p><h2 className="heading-md mt-2">Mistakes specific to this practice</h2><ul className="mt-5 grid gap-3">{practice.mistakes.map((item) => <li key={item} className="bg-camp-tan/45 px-5 py-4 font-bold leading-6 text-camp-muted">{item}</li>)}</ul></div><div><p className="eyebrow">A realistic method</p><h2 className="heading-md mt-2">Practise for control</h2><ol className="mt-5 grid gap-3">{practice.method.map((item, index) => <li key={item} className="flex gap-4 bg-camp-tan/45 px-5 py-4 font-bold leading-6 text-camp-muted"><span className="font-black text-camp-coral">{index + 1}</span>{item}</li>)}</ol></div></div></section>
      <section className="bg-camp-tan/45 py-12"><div className="page-shell grid gap-8 lg:grid-cols-2"><div><p className="eyebrow">Curriculum connection</p><h2 className="heading-md mt-2">Continue with structured lessons</h2><div className="mt-5 flex flex-wrap gap-3">{practice.curriculumLinks.map((link) => <Link key={link.href} href={link.href} className="button-primary">{link.label}</Link>)}</div></div><div><p className="eyebrow">Next practice</p><h2 className="heading-md mt-2">Keep the next activity relevant</h2><div className="mt-5 flex flex-wrap gap-x-5 gap-y-3">{practice.relatedPractice.map((link) => <Link key={link.href} href={link.href} className="font-black text-camp-coral underline decoration-2 underline-offset-4 hover:text-camp-orange focus-visible:bg-camp-orange focus-visible:text-white">{link.label}</Link>)}<Link href="/typing-test" className="font-black text-camp-coral underline decoration-2 underline-offset-4 hover:text-camp-orange focus-visible:bg-camp-orange focus-visible:text-white">Take the full typing test</Link></div></div></div></section>
      {practice.faq ? <section className="section-pad"><div className="page-shell max-w-3xl"><p className="eyebrow">About this exercise</p><h2 className="heading-md mt-2">A practical question</h2>{practice.faq.map((item) => <div key={item.question} className="mt-6"><h3 className="text-lg font-black text-camp-ink">{item.question}</h3><p className="mt-2 leading-7 text-camp-muted">{item.answer}</p></div>)}</div></section> : null}
    </>
  );
}
