import { ENABLED_CURRICULUM_LESSONS } from "@/lib/curriculum/registry";
import { PROGRESS_STORAGE_KEY } from "@/lib/progress/types";
import { THEMES, THEME_CSS_VARIABLES } from "@/lib/themes/registry";

export function buildThemeBootstrapScript() {
  const themes = THEMES.map(({ availability, id, tokens }) => ({ availability, id, tokens }));
  const lessonIds = ENABLED_CURRICULUM_LESSONS.map((lesson) => lesson.id);
  return `(function(){try{var raw=localStorage.getItem(${JSON.stringify(PROGRESS_STORAGE_KEY)});if(!raw)return;var p=JSON.parse(raw);if(!p||p.schemaVersion!==5)return;var themes=${JSON.stringify(themes)};var lessonIds=${JSON.stringify(lessonIds)};var id=p.customization&&p.customization.selectedThemeId;var theme=themes.find(function(t){return t.id===id;})||themes[0];var lessons=p.lessons||{};var records=lessonIds.map(function(k){return lessons[k]||{};});var unlocked=((p.achievements&&p.achievements.unlocked)||[]).some(function(a){return a&&a.id==='seven-day-streak';});var grandfathered=((p.customization&&p.customization.grandfatheredThemeIds)||[]).indexOf(theme.id)>=0;var available=grandfathered||theme.availability==='always'||(theme.availability==='five-lessons'&&records.filter(function(r){return (r.bestStars||0)>=1;}).length>=5)||(theme.availability==='fifteen-stars'&&records.reduce(function(n,r){return n+(r.bestStars||0);},0)>=15)||(theme.availability==='week-at-camp'&&unlocked)||(theme.availability==='three-stars-all-lessons'&&records.length===lessonIds.length&&records.every(function(r){return (r.bestStars||0)>=3;}));if(!available)theme=themes[0];var root=document.documentElement;root.dataset.theme=theme.id;var vars=${JSON.stringify(THEME_CSS_VARIABLES)};Object.keys(theme.tokens).forEach(function(k){root.style.setProperty(vars[k],theme.tokens[k]);});}catch(e){}})();`;
}
